# Generated by Django 4.2.4 on 2023-09-01 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_productmodel_image'),
        ('cart', '0005_alter_cartitemmodel_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitemmodel',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.productmodel'),
        ),
    ]
